from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams, Distance, PointStruct

from model_loader import load_model

model_name = "google/embeddinggemma-300m"
model = load_model(model_name)

client = QdrantClient(":memory:")

client.create_collection(
    collection_name="entities",
    vectors_config=VectorParams(size=768, distance=Distance.COSINE),
)

client.create_collection(
    collection_name="metrics",
    vectors_config=VectorParams(size=768, distance=Distance.COSINE),
)

metric_example_db = [
  {
    "id": "metric_001",
    "metric_name": "total_revenue",
    "description": "The total income generated by a company during a specific period.",
    "unit": "USD",
    "sql_snippet": "SUM(revenue) AS total_revenue"
  },
  {
    "id": "metric_002",
    "metric_name": "net_profit",
    "description": "The profit remaining after all expenses, taxes, and costs have been deducted from total revenue.",
    "unit": "USD",
    "sql_snippet": "(SUM(revenue) - SUM(cost) - SUM(tax)) AS net_profit"
  },
  {
    "id": "metric_003",
    "metric_name": "customer_retention_rate",
    "description": "Percentage of customers who continue to do business with the company over a given period.",
    "unit": "ratio (0–1)",
    "sql_snippet": "COUNT(DISTINCT retained_customers) / COUNT(DISTINCT total_customers) AS customer_retention_rate"
  },
  {
    "id": "metric_004",
    "metric_name": "marketing_engagement",
    "description": "Level of interaction and engagement of customers with marketing campaigns, including clicks, shares, and views.",
    "unit": "ratio (0–1)",
    "sql_snippet": "(SUM(clicks) + SUM(shares) + SUM(views)) / SUM(total_exposure) AS marketing_engagement"
  },
  {
    "id": "metric_005",
    "metric_name": "delivery_time_reduction",
    "description": "Percentage reduction in average delivery time compared to the previous period.",
    "unit": "ratio (0–1)",
    "sql_snippet": "(AVG(prev_delivery_time) - AVG(current_delivery_time)) / AVG(prev_delivery_time) AS delivery_time_reduction"
  },
  {
    "id": "metric_006",
    "metric_name": "subscription_growth",
    "description": "The rate at which new subscriptions are added over a period.",
    "unit": "ratio (0–1)",
    "sql_snippet": "(COUNT(new_subscriptions) - COUNT(old_subscriptions)) / COUNT(old_subscriptions) AS subscription_growth"
  },
  {
    "id": "metric_007",
    "metric_name": "social_media_lift",
    "description": "Percentage increase in social media engagement metrics due to campaigns.",
    "unit": "ratio (0–1)",
    "sql_snippet": "(SUM(current_engagement) - SUM(previous_engagement)) / SUM(previous_engagement) AS social_media_lift"
  },
  {
    "id": "metric_008",
    "metric_name": "market_share_growth",
    "description": "Percentage change in the company's share of the market compared to the previous period.",
    "unit": "ratio (0–1)",
    "sql_snippet": "(market_share_current - market_share_previous) / market_share_previous AS market_share_growth"
  },
  {
    "id": "metric_009",
    "metric_name": "ad_cpc_growth",
    "description": "Growth in cost-per-click (CPC) for digital advertising campaigns.",
    "unit": "ratio (0–1)",
    "sql_snippet": "(AVG(current_cpc) - AVG(previous_cpc)) / AVG(previous_cpc) AS ad_cpc_growth"
  },
  {
    "id": "metric_010",
    "metric_name": "employee_productivity_growth",
    "description": "Percentage increase in employee productivity over a period, often measured via KPIs.",
    "unit": "ratio (0–1)",
    "sql_snippet": "(AVG(current_productivity) - AVG(previous_productivity)) / AVG(previous_productivity) AS employee_productivity_growth"
  }
]

brand_example_db = [
  {
    "id": "brand_001",
    "brand": "Tesla",
    "description": "Electric vehicle and clean energy company.",
    "sql_snippet": "brand = 'Tesla'"
  },
  {
    "id": "brand_002",
    "brand": "Apple",
    "description": "Technology company known for iPhones, Macs, and subscription services.",
    "sql_snippet": "brand = 'Apple'"
  },
  {
    "id": "brand_003",
    "brand": "Nike",
    "description": "Sportswear and athletic apparel company.",
    "sql_snippet": "brand = 'Nike'"
  },
  {
    "id": "brand_004",
    "brand": "Coca-Cola",
    "description": "Beverage company producing soft drinks and other beverages.",
    "sql_snippet": "brand = 'Coca-Cola'"
  },
  {
    "id": "brand_005",
    "brand": "Amazon",
    "description": "E-commerce and cloud computing giant.",
    "sql_snippet": "brand = 'Amazon'"
  },
  {
    "id": "brand_006",
    "brand": "Google",
    "description": "Technology company specializing in search, advertising, and cloud services.",
    "sql_snippet": "brand = 'Google'"
  },
  {
    "id": "brand_007",
    "brand": "Microsoft",
    "description": "Technology company focusing on software, cloud services, and enterprise solutions.",
    "sql_snippet": "brand = 'Microsoft'"
  }
]

print("Upserting brands into Qdrant...")
for i, brand in enumerate(brand_example_db):
    vector = model.encode(
        [brand["brand"]],
        normalize_embeddings=True
    )[0]
    print(f"Text: {brand['brand']}, Vector shape: {vector.shape}")
    client.upsert(
        collection_name="entities",
        points=[
            PointStruct(
                id=i,
                vector=vector.tolist(),
                payload={
                    "text": brand["brand"],
                    "description": brand["description"],
                    "sql_snippet": brand["sql_snippet"]
                }
            )
        ]
    )
    print(f"Upserted brand: {brand['brand']} with ID: {brand['id']}")

print("Upserting metrics into Qdrant...")
for i, metric in enumerate(metric_example_db):
    vector = model.encode(
        [metric["metric_name"]],
        normalize_embeddings=True
    )[0]
    print(f"Text: {metric['metric_name']}, Vector shape: {vector.shape}")
    client.upsert(
        collection_name="metrics",
        points=[
            PointStruct(
                id=i,
                vector=vector.tolist(),
                payload={
                    "text": metric["metric_name"],
                    "description": metric["description"],
                    "sql_snippet": metric["sql_snippet"]
                }
            )
        ]
    )