"""new additional tables

Revision ID: 01c02b3e9d72
Revises: 598c70f5e70d
Create Date: 2026-05-13 15:07:09.337620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c02b3e9d72'
down_revision: Union[str, Sequence[str], None] = '598c70f5e70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=True),
    sa.Column('retailer_clean_id', sa.UUID(), nullable=True),
    sa.Column('advertiser_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('product_category_id', sa.UUID(), nullable=True),
    sa.Column('brand_category_id', sa.UUID(), nullable=True),
    sa.Column('first_appearance_date', sa.Date(), nullable=True),
    sa.Column('last_appearance_date', sa.Date(), nullable=True),
    sa.Column('data_type', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('declined', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertisement_add_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('add_id', sa.UUID(), nullable=False),
    sa.Column('add_category_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertisement_bools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('add_id', sa.UUID(), nullable=False),
    sa.Column('key_player', sa.Boolean(), nullable=True),
    sa.Column('referent_market', sa.Boolean(), nullable=True),
    sa.Column('packed_chocolate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertisement_brand',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('add_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertisement_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('add_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertisement_format',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('add_id', sa.UUID(), nullable=False),
    sa.Column('format_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertisement_link',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('add_id', sa.UUID(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('appearance_period', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertisement_price',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('add_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisement_price')
    op.drop_table('advertisement_link')
    op.drop_table('advertisement_format')
    op.drop_table('advertisement_category')
    op.drop_table('advertisement_brand')
    op.drop_table('advertisement_bools')
    op.drop_table('advertisement_add_category')
    op.drop_table('advertisement')
    # ### end Alembic commands ###
