"""replace_ecom_funnel_with_new_dict_tables

Revision ID: 10c767b2b523
Revises: i6j7k8l9m0n1
Create Date: 2026-05-13 13:38:42.066567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10c767b2b523'
down_revision: Union[str, Sequence[str], None] = 'i6j7k8l9m0n1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_processed',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('weekly_price', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('retail_processed_id', sa.UUID(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=True),
    sa.Column('Ретейлер clean', sa.Text(), nullable=True),
    sa.Column('Advertiser (producer)', sa.Text(), nullable=True),
    sa.Column('Brands list', sa.Text(), nullable=True),
    sa.Column('Brands list clean', sa.Text(), nullable=True),
    sa.Column('!Категория Ферреро', sa.Text(), nullable=True),
    sa.Column('!Категория Ферреро  (Range категорий)', sa.Text(), nullable=True),
    sa.Column('!Категория Ферреро (Мультибренд ка', sa.Text(), nullable=True),
    sa.Column('Дата первого скрина', sa.Date(), nullable=True),
    sa.Column('Дата последнего скрина', sa.Date(), nullable=True),
    sa.Column('Advertisement ID', sa.Text(), nullable=True),
    sa.Column('advertising_category', sa.Text(), nullable=True),
    sa.Column('is_seasonal', sa.Boolean(), nullable=True),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('days_monitored_est', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('declined', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retail_multi_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('picture_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('value', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retail_processed',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('retailer_clean', sa.Text(), nullable=False),
    sa.Column('advertiser_producer', sa.Text(), nullable=False),
    sa.Column('brands_list_clean', sa.Text(), nullable=False),
    sa.Column('ferrero_category_range', sa.Text(), nullable=False),
    sa.Column('ferrero_category_multibrand', sa.Text(), nullable=False),
    sa.Column('first_screen_date', sa.Date(), nullable=False),
    sa.Column('last_screen_date', sa.Date(), nullable=False),
    sa.Column('advertisement_id', sa.Text(), nullable=False),
    sa.Column('advertising_category', sa.Text(), nullable=True),
    sa.Column('seasonal', sa.Boolean(), nullable=True),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('estimated_days', sa.Text(), nullable=False),
    sa.Column('group_id', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('advertisement_price')
    op.drop_table('advertisement_format')
    op.drop_table('advertisement_add_category')
    op.drop_table('advertisement_brand')
    op.drop_table('advertisement_link')
    op.drop_table('advertisement_category')
    op.drop_table('advertisement_bools')
    op.drop_table('advertisement')
    op.add_column('detector_format_comparison', sa.Column('retailer_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detector_format_comparison', 'retailer_id')
    op.create_table('advertisement',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('process_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('retailer_clean_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('advertiser_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('brand_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('product_category_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('brand_category_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('first_appearance_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('last_appearance_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('declined', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('advertisement_pkey'))
    )
    op.create_table('advertisement_bools',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('add_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key_player', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('referent_market', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('packed_chocolate', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('advertisement_bools_pkey'))
    )
    op.create_table('advertisement_category',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('add_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('advertisement_category_pkey'))
    )
    op.create_table('advertisement_link',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('add_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('appearance_period', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('advertisement_link_pkey'))
    )
    op.create_table('advertisement_brand',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('add_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('advertisement_brand_pkey'))
    )
    op.create_table('advertisement_add_category',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('add_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('add_category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('advertisement_add_category_pkey'))
    )
    op.create_table('advertisement_format',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('add_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('format_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('advertisement_format_pkey'))
    )
    op.create_table('advertisement_price',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('add_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('advertisement_price_pkey'))
    )
    op.drop_table('retail_processed')
    op.drop_table('retail_multi_values')
    op.drop_table('retail')
    op.drop_table('analyst_processed')
    # ### end Alembic commands ###
