"""format for dettector table column change

Revision ID: 4229f584f8b2
Revises: h5i6j7k8l9m0
Create Date: 2026-05-09 00:28:38.799602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4229f584f8b2'
down_revision: Union[str, Sequence[str], None] = 'h5i6j7k8l9m0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecom_format_for_detector', sa.Column('retailer_id', sa.Text(), nullable=True))
    op.drop_column('ecom_format_for_detector', 'retailer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecom_format_for_detector', sa.Column('retailer_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('ecom_format_for_detector', 'retailer_id')
    # ### end Alembic commands ###
