"""rebuild

Revision ID: 598c70f5e70d
Revises: 10c767b2b523
Create Date: 2026-05-13 14:52:44.890366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598c70f5e70d'
down_revision: Union[str, Sequence[str], None] = '10c767b2b523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_value',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('column_name_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simple_value')
    # ### end Alembic commands ###
