"""admin table refactoring

Revision ID: 6d06417cb6ec
Revises: g4h5i6j7k8l9
Create Date: 2026-05-07 14:02:27.855180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d06417cb6ec'
down_revision: Union[str, Sequence[str], None] = 'g4h5i6j7k8l9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_admin_settings', sa.Column('uploadable', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('table_admin_settings', sa.Column('upload_prefix', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_admin_settings', 'upload_prefix')
    op.drop_column('table_admin_settings', 'uploadable')
    # ### end Alembic commands ###
