"""funnel stage table

Revision ID: 6e318eec7643
Revises: fa599be78954
Create Date: 2026-05-09 00:19:07.671059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e318eec7643'
down_revision: Union[str, Sequence[str], None] = 'fa599be78954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funnel_stage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('funnel_stage_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funnel_stage')
    # ### end Alembic commands ###
