"""rename_picture_processing_add_process_types_statuses_processes_move_retail

Revision ID: 8e069dfe2de2
Revises: ca41582f48e0
Create Date: 2026-04-02 16:21:18.953785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e069dfe2de2'
down_revision: Union[str, Sequence[str], None] = 'ca41582f48e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('process_status_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('process_type_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('initiator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retail_upload_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('Ретейлер clean', sa.Text(), nullable=True),
    sa.Column('Advertiser (producer)', sa.Text(), nullable=True),
    sa.Column('Brands list', sa.Text(), nullable=True),
    sa.Column('Brands list clean', sa.Text(), nullable=True),
    sa.Column('!Категория Ферреро', sa.Text(), nullable=True),
    sa.Column('!Категория Ферреро  (Range категорий)', sa.Text(), nullable=True),
    sa.Column('!Категория Ферреро (Мультибренд категорий)', sa.Text(), nullable=True),
    sa.Column('Дата первого скрина', sa.Date(), nullable=True),
    sa.Column('Дата последнего скрина', sa.Date(), nullable=True),
    sa.Column('Advertisement ID', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retail_upload_rows_additional',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('retail_upload_row_id', sa.UUID(), nullable=False),
    sa.Column('Key player', sa.Boolean(), nullable=False),
    sa.Column('Referent Market', sa.Boolean(), nullable=False),
    sa.Column('Packed Chocolate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('picture_processing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture_processing',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.TEXT(), server_default=sa.text("'retail'::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('picture_processing_pkey'))
    )
    op.drop_table('retail_upload_rows_additional')
    op.drop_table('retail_upload_rows')
    op.drop_table('processes')
    op.drop_table('process_types')
    op.drop_table('process_statuses')
    op.drop_table('process_settings')
    # ### end Alembic commands ###
