"""new dictionaries tables

Revision ID: 9707aa74442c
Revises: a4b5c6d7e8f9
Create Date: 2026-05-07 13:15:48.456523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9707aa74442c'
down_revision: Union[str, Sequence[str], None] = 'a4b5c6d7e8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecom_format',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('retailer_name', sa.Text(), nullable=True),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('sov', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecom_format_for_detector',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('retailer_name', sa.Text(), nullable=True),
    sa.Column('format_detector', sa.Text(), nullable=True),
    sa.Column('format_correct', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('retail_multi_values')
    # ### end Alembic commands ###
