"""format for dettector table column change

Revision ID: aa38eac6e73d
Revises: 4229f584f8b2
Create Date: 2026-05-09 00:29:32.549028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa38eac6e73d'
down_revision: Union[str, Sequence[str], None] = '4229f584f8b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecom_format_for_detector', 'retailer_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='retailer_id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecom_format_for_detector', 'retailer_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
