"""deletion of old tables

Revision ID: c183b5255915
Revises: 9707aa74442c
Create Date: 2026-05-07 13:48:26.089659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c183b5255915'
down_revision: Union[str, Sequence[str], None] = '9707aa74442c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retail_process_additional')
    op.add_column('retail_processed', sa.Column('advertising_category', sa.Text(), nullable=True))
    op.add_column('retail_processed', sa.Column('seasonal', sa.Boolean(), nullable=True))
    op.add_column('retail_processed', sa.Column('format', sa.Text(), nullable=False))
    op.add_column('retail_processed', sa.Column('estimated_days', sa.Text(), nullable=False))
    op.add_column('retail_processed', sa.Column('group_id', sa.Text(), nullable=True))
    op.alter_column('retail_processed', 'retailer_clean',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('retail_processed', 'advertiser_producer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('retail_processed', 'brands_list_clean',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('retail_processed', 'ferrero_category_range',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('retail_processed', 'ferrero_category_multibrand',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('retail_processed', 'first_screen_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('retail_processed', 'last_screen_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('retail_processed', 'advertisement_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('retail_processed', 'ferrero_category')
    op.drop_column('retail_processed', 'brands_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retail_processed', sa.Column('brands_list', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('retail_processed', sa.Column('ferrero_category', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('retail_processed', 'advertisement_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('retail_processed', 'last_screen_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('retail_processed', 'first_screen_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('retail_processed', 'ferrero_category_multibrand',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('retail_processed', 'ferrero_category_range',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('retail_processed', 'brands_list_clean',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('retail_processed', 'advertiser_producer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('retail_processed', 'retailer_clean',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('retail_processed', 'group_id')
    op.drop_column('retail_processed', 'estimated_days')
    op.drop_column('retail_processed', 'format')
    op.drop_column('retail_processed', 'seasonal')
    op.drop_column('retail_processed', 'advertising_category')
    op.add_column('retail', sa.Column('!Категория Ферреро (Мультибренд ка', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('retail', '!Категория Ферреро (Мультибренд категорий)')
    op.create_table('retail_process_additional',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('retail_upload_row_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('Key player', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('Referent Market', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('Packed Chocolate', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('retail_process_additional_pkey'))
    )
    # ### end Alembic commands ###
