"""ecom formats update

Revision ID: c9fa80dca1d5
Revises: 6d06417cb6ec
Create Date: 2026-05-09 00:09:17.218090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9fa80dca1d5'
down_revision: Union[str, Sequence[str], None] = '6d06417cb6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecom_format', sa.Column('retailer_id', sa.UUID(), nullable=True))
    op.add_column('ecom_format', sa.Column('funnel_stage_id', sa.UUID(), nullable=True))
    op.alter_column('ecom_format', 'sov',
               existing_type=sa.TEXT(),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_column('ecom_format', 'stage')
    op.drop_column('ecom_format', 'retailer_name')
    op.add_column('ecom_format_for_detector', sa.Column('format', sa.Text(), nullable=True))
    op.drop_column('ecom_format_for_detector', 'format_correct')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecom_format_for_detector', sa.Column('format_correct', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('ecom_format_for_detector', 'format')
    op.add_column('ecom_format', sa.Column('retailer_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ecom_format', sa.Column('stage', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('ecom_format', 'sov',
               existing_type=sa.FLOAT(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('ecom_format', 'funnel_stage_id')
    op.drop_column('ecom_format', 'retailer_id')
    # ### end Alembic commands ###
