"""add_table_name_and_reference_type_id

Revision ID: ca41582f48e0
Revises: 660b16f88c0d
Create Date: 2026-04-02 14:35:53.463746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca41582f48e0'
down_revision: Union[str, Sequence[str], None] = '660b16f88c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture_processing', sa.Column('table_name', sa.Text(), server_default='retail', nullable=False))
    op.add_column('process_attributes', sa.Column('reference_type_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process_attributes', 'reference_type_id')
    op.drop_column('picture_processing', 'table_name')
    # ### end Alembic commands ###
