"""remove_retail_tables_moved_to_reference

Revision ID: 980ba7a19e01
Revises: d46d089a0273
Create Date: 2026-04-02 16:22:26.682467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '980ba7a19e01'
down_revision: Union[str, Sequence[str], None] = 'd46d089a0273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retail_upload_rows')
    op.drop_table('retail_upload_rows_additional')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retail_upload_rows_additional',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('retail_upload_row_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('Key player', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('Referent Market', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('Packed Chocolate', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('retail_upload_rows_additional_pkey'))
    )
    op.create_table('retail_upload_rows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('Ретейлер clean', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Advertiser (producer)', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Brands list', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Brands list clean', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('!Категория Ферреро', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('!Категория Ферреро  (Range категорий)', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('!Категория Ферреро (Мультибренд ка', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Дата первого скрина', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Дата последнего скрина', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Advertisement ID', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('retail_upload_rows_pkey'))
    )
    # ### end Alembic commands ###
