metric_example_db = [
  {
    "metric_name": "total_revenue",
    "description": "The total income generated by a company during a specific period.",
    "unit": "USD",
    "sql_snippet": "SUM(revenue) AS total_revenue"
  },
  {
    "metric_name": "net_profit",
    "description": "The profit remaining after all expenses, taxes, and costs have been deducted from total revenue.",
    "unit": "USD",
    "sql_snippet": "(SUM(revenue) - SUM(cost) - SUM(tax)) AS net_profit"
  },
  {
    "metric_name": "customer_retention_rate",
    "description": "Percentage of customers who continue to do business with the company over a given period.",
    "unit": "ratio (0–1)",
    "sql_snippet": "COUNT(DISTINCT retained_customers) / COUNT(DISTINCT total_customers) AS customer_retention_rate"
  },
  {
    "metric_name": "marketing_engagement",
    "description": "Level of interaction and engagement of customers with marketing campaigns, including clicks, shares, and views.",
    "unit": "ratio (0–1)",
    "sql_snippet": "(SUM(clicks) + SUM(shares) + SUM(views)) / SUM(total_exposure) AS marketing_engagement"
  },
  {
    "metric_name": "delivery_time_reduction",
    "description": "Percentage reduction in average delivery time compared to the previous period.",
    "unit": "ratio (0–1)",
    "sql_snippet": "(AVG(prev_delivery_time) - AVG(current_delivery_time)) / AVG(prev_delivery_time) AS delivery_time_reduction"
  },
  {
    "metric_name": "subscription_growth",
    "description": "The rate at which new subscriptions are added over a period.",
    "unit": "ratio (0–1)",
    "sql_snippet": "(COUNT(new_subscriptions) - COUNT(old_subscriptions)) / COUNT(old_subscriptions) AS subscription_growth"
  },
  {
    "metric_name": "social_media_lift",
    "description": "Percentage increase in social media engagement metrics due to campaigns.",
    "unit": "ratio (0–1)",
    "sql_snippet": "(SUM(current_engagement) - SUM(previous_engagement)) / SUM(previous_engagement) AS social_media_lift"
  },
  {
    "metric_name": "market_share_growth",
    "description": "Percentage change in the company's share of the market compared to the previous period.",
    "unit": "ratio (0–1)",
    "sql_snippet": "(market_share_current - market_share_previous) / market_share_previous AS market_share_growth"
  },
  {
    "metric_name": "ad_cpc_growth",
    "description": "Growth in cost-per-click (CPC) for digital advertising campaigns.",
    "unit": "ratio (0–1)",
    "sql_snippet": "(AVG(current_cpc) - AVG(previous_cpc)) / AVG(previous_cpc) AS ad_cpc_growth"
  },
  {
    "metric_name": "employee_productivity_growth",
    "description": "Percentage increase in employee productivity over a period, often measured via KPIs.",
    "unit": "ratio (0–1)",
    "sql_snippet": "(AVG(current_productivity) - AVG(previous_productivity)) / AVG(previous_productivity) AS employee_productivity_growth"
  }
]

brand_example_db = [
  {
    "brand": "Tesla",
    "description": "Electric vehicle and clean energy company.",
    "sql_snippet": "brand = 'Tesla'"
  },
  {
    "brand": "Apple",
    "description": "Technology company known for iPhones, Macs, and subscription services.",
    "sql_snippet": "brand = 'Apple'"
  },
  {
    "brand": "Nike",
    "description": "Sportswear and athletic apparel company.",
    "sql_snippet": "brand = 'Nike'"
  },
  {
    "brand": "Coca-Cola",
    "description": "Beverage company producing soft drinks and other beverages.",
    "sql_snippet": "brand = 'Coca-Cola'"
  },
  {
    "brand": "Amazon",
    "description": "E-commerce and cloud computing giant.",
    "sql_snippet": "brand = 'Amazon'"
  },
  {
    "brand": "Google",
    "description": "Technology company specializing in search, advertising, and cloud services.",
    "sql_snippet": "brand = 'Google'"
  },
  {
    "brand": "Microsoft",
    "description": "Technology company focusing on software, cloud services, and enterprise solutions.",
    "sql_snippet": "brand = 'Microsoft'"
  }
]